// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKj78ZIjPEtGY_9iZoIIredxr5clrojEs',
    appId: '1:1081879660957:web:8a92521d74d49ae8424774',
    messagingSenderId: '1081879660957',
    projectId: 'scholar-chat-b22ee',
    authDomain: 'scholar-chat-b22ee.firebaseapp.com',
    storageBucket: 'scholar-chat-b22ee.appspot.com',
    measurementId: 'G-8E3RGBLTEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qfhutYW076149OudtjPvfDEzMAMdQ5U',
    appId: '1:1081879660957:android:225d480db14e5e91424774',
    messagingSenderId: '1081879660957',
    projectId: 'scholar-chat-b22ee',
    storageBucket: 'scholar-chat-b22ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwcaEhxlX2V4ivKOGcQBnx_Ypkj44all0',
    appId: '1:1081879660957:ios:fb9a23cb5193eb0a424774',
    messagingSenderId: '1081879660957',
    projectId: 'scholar-chat-b22ee',
    storageBucket: 'scholar-chat-b22ee.appspot.com',
    iosClientId: '1081879660957-0jtr1vhggdu5ino78kmafr7o78u2qqcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwcaEhxlX2V4ivKOGcQBnx_Ypkj44all0',
    appId: '1:1081879660957:ios:fb9a23cb5193eb0a424774',
    messagingSenderId: '1081879660957',
    projectId: 'scholar-chat-b22ee',
    storageBucket: 'scholar-chat-b22ee.appspot.com',
    iosClientId: '1081879660957-0jtr1vhggdu5ino78kmafr7o78u2qqcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
